package com.fitnesstime.fitnesstime.DAO;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.fitnesstime.fitnesstime.Dominio.Ejercicio;
import com.fitnesstime.fitnesstime.Dominio.Marca;
import com.fitnesstime.fitnesstime.Dominio.Paso;
import com.fitnesstime.fitnesstime.Dominio.Rutina;
import com.fitnesstime.fitnesstime.Dominio.SecurityToken;

import com.fitnesstime.fitnesstime.DAO.EjercicioDao;
import com.fitnesstime.fitnesstime.DAO.MarcaDao;
import com.fitnesstime.fitnesstime.DAO.RutinaDao;
import com.fitnesstime.fitnesstime.DAO.SecurityTokenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig ejercicioDaoConfig;
    private final DaoConfig marcaDaoConfig;
    private final DaoConfig rutinaDaoConfig;
    private final DaoConfig securityTokenDaoConfig;
    private final DaoConfig pasoDaoConfig;

    private final EjercicioDao ejercicioDao;
    private final MarcaDao marcaDao;
    private final RutinaDao rutinaDao;
    private final SecurityTokenDao securityTokenDao;
    private final PasoDao pasoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        ejercicioDaoConfig = daoConfigMap.get(EjercicioDao.class).clone();
        ejercicioDaoConfig.initIdentityScope(type);

        marcaDaoConfig = daoConfigMap.get(MarcaDao.class).clone();
        marcaDaoConfig.initIdentityScope(type);

        rutinaDaoConfig = daoConfigMap.get(RutinaDao.class).clone();
        rutinaDaoConfig.initIdentityScope(type);

        securityTokenDaoConfig = daoConfigMap.get(SecurityTokenDao.class).clone();
        securityTokenDaoConfig.initIdentityScope(type);

        pasoDaoConfig = daoConfigMap.get(PasoDao.class).clone();
        pasoDaoConfig.initIdentityScope(type);

        ejercicioDao = new EjercicioDao(ejercicioDaoConfig, this);
        marcaDao = new MarcaDao(marcaDaoConfig, this);
        rutinaDao = new RutinaDao(rutinaDaoConfig, this);
        securityTokenDao = new SecurityTokenDao(securityTokenDaoConfig, this);
        pasoDao = new PasoDao(pasoDaoConfig, this);

        registerDao(Ejercicio.class, ejercicioDao);
        registerDao(Marca.class, marcaDao);
        registerDao(Rutina.class, rutinaDao);
        registerDao(SecurityToken.class, securityTokenDao);
        registerDao(Paso.class, pasoDao);
    }
    
    public void clear() {
        ejercicioDaoConfig.getIdentityScope().clear();
        marcaDaoConfig.getIdentityScope().clear();
        rutinaDaoConfig.getIdentityScope().clear();
        securityTokenDaoConfig.getIdentityScope().clear();
        pasoDaoConfig.getIdentityScope().clear();
    }

    public EjercicioDao getEjercicioDao() {
        return ejercicioDao;
    }

    public MarcaDao getMarcaDao() {
        return marcaDao;
    }

    public RutinaDao getRutinaDao() {
        return rutinaDao;
    }

    public SecurityTokenDao getSecurityTokenDao() {
        return securityTokenDao;
    }

    public PasoDao getPasoDao() {
        return pasoDao;
    }

}
