package com.fitnesstime.fitnesstime.DAO;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.fitnesstime.fitnesstime.Dominio.Ejercicio;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EJERCICIO".
*/
public class EjercicioDao extends AbstractDao<Ejercicio, Long> {

    public static final String TABLENAME = "EJERCICIO";

    /**
     * Properties of entity Ejercicio.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Nombre = new Property(1, String.class, "nombre", false, "NOMBRE");
        public final static Property DiaDeLaSemana = new Property(2, String.class, "diaDeLaSemana", false, "DIA_DE_LA_SEMANA");
        public final static Property Series = new Property(3, Integer.class, "series", false, "SERIES");
        public final static Property Repeticiones = new Property(4, Integer.class, "repeticiones", false, "REPETICIONES");
        public final static Property TiempoActivo = new Property(5, Integer.class, "tiempoActivo", false, "TIEMPO_ACTIVO");
        public final static Property TiempoDescanso = new Property(6, Integer.class, "tiempoDescanso", false, "TIEMPO_DESCANSO");
        public final static Property EsDeCarga = new Property(7, boolean.class, "esDeCarga", false, "ES_DE_CARGA");
        public final static Property RutinaId = new Property(8, long.class, "rutinaId", false, "RUTINA_ID");
    };

    private Query<Ejercicio> rutina_EjercicioListQuery;

    public EjercicioDao(DaoConfig config) {
        super(config);
    }
    
    public EjercicioDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EJERCICIO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NOMBRE\" TEXT NOT NULL ," + // 1: nombre
                "\"DIA_DE_LA_SEMANA\" TEXT," + // 2: diaDeLaSemana
                "\"SERIES\" INTEGER," + // 3: series
                "\"REPETICIONES\" INTEGER," + // 4: repeticiones
                "\"TIEMPO_ACTIVO\" INTEGER," + // 5: tiempoActivo
                "\"TIEMPO_DESCANSO\" INTEGER," + // 6: tiempoDescanso
                "\"ES_DE_CARGA\" INTEGER NOT NULL ," + // 7: esDeCarga
                "\"RUTINA_ID\" INTEGER NOT NULL );"); // 8: rutinaId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EJERCICIO\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Ejercicio entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getNombre());
 
        String diaDeLaSemana = entity.getDiaDeLaSemana();
        if (diaDeLaSemana != null) {
            stmt.bindString(3, diaDeLaSemana);
        }
 
        Integer series = entity.getSeries();
        if (series != null) {
            stmt.bindLong(4, series);
        }
 
        Integer repeticiones = entity.getRepeticiones();
        if (repeticiones != null) {
            stmt.bindLong(5, repeticiones);
        }
 
        Integer tiempoActivo = entity.getTiempoActivo();
        if (tiempoActivo != null) {
            stmt.bindLong(6, tiempoActivo);
        }
 
        Integer tiempoDescanso = entity.getTiempoDescanso();
        if (tiempoDescanso != null) {
            stmt.bindLong(7, tiempoDescanso);
        }
        stmt.bindLong(8, entity.getEsDeCarga() ? 1L: 0L);
        stmt.bindLong(9, entity.getRutinaId());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Ejercicio readEntity(Cursor cursor, int offset) {
        Ejercicio entity = new Ejercicio( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // nombre
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // diaDeLaSemana
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // series
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // repeticiones
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // tiempoActivo
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // tiempoDescanso
            cursor.getShort(offset + 7) != 0, // esDeCarga
            cursor.getLong(offset + 8) // rutinaId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Ejercicio entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNombre(cursor.getString(offset + 1));
        entity.setDiaDeLaSemana(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSeries(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setRepeticiones(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setTiempoActivo(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setTiempoDescanso(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setEsDeCarga(cursor.getShort(offset + 7) != 0);
        entity.setRutinaId(cursor.getLong(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Ejercicio entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Ejercicio entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "ejercicioList" to-many relationship of Rutina. */
    public List<Ejercicio> _queryRutina_EjercicioList(long rutinaId) {
        synchronized (this) {
            if (rutina_EjercicioListQuery == null) {
                QueryBuilder<Ejercicio> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.RutinaId.eq(null));
                rutina_EjercicioListQuery = queryBuilder.build();
            }
        }
        Query<Ejercicio> query = rutina_EjercicioListQuery.forCurrentThread();
        query.setParameter(0, rutinaId);
        return query.list();
    }

}
