package com.fitnesstime.fitnesstime.DAO;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.fitnesstime.fitnesstime.Dominio.Rutina;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RUTINA".
*/
public class RutinaDao extends AbstractDao<Rutina, Long> {

    public static final String TABLENAME = "RUTINA";

    /**
     * Properties of entity Rutina.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IdUsuario = new Property(1, String.class, "idUsuario", false, "ID_USUARIO");
        public final static Property Descripcion = new Property(2, String.class, "descripcion", false, "DESCRIPCION");
        public final static Property Aclaracion = new Property(3, String.class, "aclaracion", false, "ACLARACION");
        public final static Property FechaInicio = new Property(4, String.class, "fechaInicio", false, "FECHA_INICIO");
        public final static Property FechaFin = new Property(5, String.class, "fechaFin", false, "FECHA_FIN");
        public final static Property EsDeCarga = new Property(6, boolean.class, "esDeCarga", false, "ES_DE_CARGA");
    };

    private DaoSession daoSession;


    public RutinaDao(DaoConfig config) {
        super(config);
    }
    
    public RutinaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RUTINA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ID_USUARIO\" TEXT NOT NULL ," + // 1: idUsuario
                "\"DESCRIPCION\" TEXT," + // 2: descripcion
                "\"ACLARACION\" TEXT," + // 3: aclaracion
                "\"FECHA_INICIO\" TEXT," + // 4: fechaInicio
                "\"FECHA_FIN\" TEXT," + // 5: fechaFin
                "\"ES_DE_CARGA\" INTEGER NOT NULL );"); // 6: esDeCarga
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RUTINA\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Rutina entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getIdUsuario());
 
        String descripcion = entity.getDescripcion();
        if (descripcion != null) {
            stmt.bindString(3, descripcion);
        }
 
        String aclaracion = entity.getAclaracion();
        if (aclaracion != null) {
            stmt.bindString(4, aclaracion);
        }
 
        String fechaInicio = entity.getFechaInicio();
        if (fechaInicio != null) {
            stmt.bindString(5, fechaInicio);
        }
 
        String fechaFin = entity.getFechaFin();
        if (fechaFin != null) {
            stmt.bindString(6, fechaFin);
        }
        stmt.bindLong(7, entity.getEsDeCarga() ? 1L: 0L);
    }

    @Override
    protected void attachEntity(Rutina entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Rutina readEntity(Cursor cursor, int offset) {
        Rutina entity = new Rutina( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // idUsuario
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // descripcion
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // aclaracion
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // fechaInicio
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // fechaFin
            cursor.getShort(offset + 6) != 0 // esDeCarga
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Rutina entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdUsuario(cursor.getString(offset + 1));
        entity.setDescripcion(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAclaracion(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setFechaInicio(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setFechaFin(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setEsDeCarga(cursor.getShort(offset + 6) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Rutina entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Rutina entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
