package com.fitnesstime.fitnesstime.DAO;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.fitnesstime.fitnesstime.Dominio.Rutina;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RUTINA".
*/
public class RutinaDao extends AbstractDao<Rutina, Long> {

    public static final String TABLENAME = "RUTINA";

    /**
     * Properties of entity Rutina.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IdUsuario = new Property(1, String.class, "idUsuario", false, "ID_USUARIO");
        public final static Property VersionWeb = new Property(2, int.class, "versionWeb", false, "VERSION_WEB");
        public final static Property EstaSincronizado = new Property(3, boolean.class, "estaSincronizado", false, "ESTA_SINCRONIZADO");
        public final static Property Descripcion = new Property(4, String.class, "descripcion", false, "DESCRIPCION");
        public final static Property Aclaracion = new Property(5, String.class, "aclaracion", false, "ACLARACION");
        public final static Property Inicio = new Property(6, String.class, "inicio", false, "INICIO");
        public final static Property Fin = new Property(7, String.class, "fin", false, "FIN");
        public final static Property EsDeCarga = new Property(8, boolean.class, "esDeCarga", false, "ES_DE_CARGA");
    };

    private DaoSession daoSession;


    public RutinaDao(DaoConfig config) {
        super(config);
    }
    
    public RutinaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RUTINA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ID_USUARIO\" TEXT NOT NULL ," + // 1: idUsuario
                "\"VERSION_WEB\" INTEGER NOT NULL ," + // 2: versionWeb
                "\"ESTA_SINCRONIZADO\" INTEGER NOT NULL ," + // 3: estaSincronizado
                "\"DESCRIPCION\" TEXT," + // 4: descripcion
                "\"ACLARACION\" TEXT," + // 5: aclaracion
                "\"INICIO\" TEXT," + // 6: inicio
                "\"FIN\" TEXT," + // 7: fin
                "\"ES_DE_CARGA\" INTEGER NOT NULL );"); // 8: esDeCarga
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RUTINA\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Rutina entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getIdUsuario());
        stmt.bindLong(3, entity.getVersionWeb());
        stmt.bindLong(4, entity.getEstaSincronizado() ? 1L: 0L);
 
        String descripcion = entity.getDescripcion();
        if (descripcion != null) {
            stmt.bindString(5, descripcion);
        }
 
        String aclaracion = entity.getAclaracion();
        if (aclaracion != null) {
            stmt.bindString(6, aclaracion);
        }
 
        String inicio = entity.getInicio();
        if (inicio != null) {
            stmt.bindString(7, inicio);
        }
 
        String fin = entity.getFin();
        if (fin != null) {
            stmt.bindString(8, fin);
        }
        stmt.bindLong(9, entity.getEsDeCarga() ? 1L: 0L);
    }

    @Override
    protected void attachEntity(Rutina entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Rutina readEntity(Cursor cursor, int offset) {
        Rutina entity = new Rutina( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // idUsuario
            cursor.getInt(offset + 2), // versionWeb
            cursor.getShort(offset + 3) != 0, // estaSincronizado
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // descripcion
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // aclaracion
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // inicio
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // fin
            cursor.getShort(offset + 8) != 0 // esDeCarga
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Rutina entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdUsuario(cursor.getString(offset + 1));
        entity.setVersionWeb(cursor.getInt(offset + 2));
        entity.setEstaSincronizado(cursor.getShort(offset + 3) != 0);
        entity.setDescripcion(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setAclaracion(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setInicio(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setFin(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setEsDeCarga(cursor.getShort(offset + 8) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Rutina entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Rutina entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
