package com.fitnesstime.fitnesstime.Dominio;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "EJERCICIO".
 */
public class Ejercicio implements DomainEntity {

    private Long id;
    private Long idWeb;
    private Integer versionWeb;
    private Integer version;
    /** Not-null value. */
    private String nombre;
    private boolean estaSincronizado;
    private String diaDeLaSemana;
    private Integer series;
    private Integer repeticiones;
    private Integer tiempoActivo;
    private Integer tiempoDescanso;
    private boolean eliminada;
    private boolean esDeCarga;
    private long rutinaId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Ejercicio() {
    }

    public Ejercicio(Long id) {
        this.id = id;
    }

    public Ejercicio(Long id, Long idWeb, Integer versionWeb, Integer version, String nombre, boolean estaSincronizado, String diaDeLaSemana, Integer series, Integer repeticiones, Integer tiempoActivo, Integer tiempoDescanso, boolean eliminada, boolean esDeCarga, long rutinaId) {
        this.id = id;
        this.idWeb = idWeb;
        this.versionWeb = versionWeb;
        this.version = version;
        this.nombre = nombre;
        this.estaSincronizado = estaSincronizado;
        this.diaDeLaSemana = diaDeLaSemana;
        this.series = series;
        this.repeticiones = repeticiones;
        this.tiempoActivo = tiempoActivo;
        this.tiempoDescanso = tiempoDescanso;
        this.eliminada = eliminada;
        this.esDeCarga = esDeCarga;
        this.rutinaId = rutinaId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getIdWeb() {
        return idWeb;
    }

    public void setIdWeb(Long idWeb) {
        this.idWeb = idWeb;
    }

    public Integer getVersionWeb() {
        return versionWeb;
    }

    public void setVersionWeb(Integer versionWeb) {
        this.versionWeb = versionWeb;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    /** Not-null value. */
    public String getNombre() {
        return nombre;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public boolean getEstaSincronizado() {
        return estaSincronizado;
    }

    public void setEstaSincronizado(boolean estaSincronizado) {
        this.estaSincronizado = estaSincronizado;
    }

    public String getDiaDeLaSemana() {
        return diaDeLaSemana;
    }

    public void setDiaDeLaSemana(String diaDeLaSemana) {
        this.diaDeLaSemana = diaDeLaSemana;
    }

    public Integer getSeries() {
        return series;
    }

    public void setSeries(Integer series) {
        this.series = series;
    }

    public Integer getRepeticiones() {
        return repeticiones;
    }

    public void setRepeticiones(Integer repeticiones) {
        this.repeticiones = repeticiones;
    }

    public Integer getTiempoActivo() {
        return tiempoActivo;
    }

    public void setTiempoActivo(Integer tiempoActivo) {
        this.tiempoActivo = tiempoActivo;
    }

    public Integer getTiempoDescanso() {
        return tiempoDescanso;
    }

    public void setTiempoDescanso(Integer tiempoDescanso) {
        this.tiempoDescanso = tiempoDescanso;
    }

    public boolean getEliminada() {
        return eliminada;
    }

    public void setEliminada(boolean eliminada) {
        this.eliminada = eliminada;
    }

    public boolean getEsDeCarga() {
        return esDeCarga;
    }

    public void setEsDeCarga(boolean esDeCarga) {
        this.esDeCarga = esDeCarga;
    }

    public long getRutinaId() {
        return rutinaId;
    }

    public void setRutinaId(long rutinaId) {
        this.rutinaId = rutinaId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
