package com.fitnesstime.fitnesstime.Dominio;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "EJERCICIO".
 */
public class Ejercicio implements DomainEntity{

    private Long id;
    private long rutinaId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Ejercicio() {
    }

    public Ejercicio(Long id) {
        this.id = id;
    }

    public Ejercicio(Long id, long rutinaId) {
        this.id = id;
        this.rutinaId = rutinaId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getRutinaId() {
        return rutinaId;
    }

    public void setRutinaId(long rutinaId) {
        this.rutinaId = rutinaId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
