package com.fitnesstime.fitnesstime.Dominio;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "MARCA".
 */
public class Marca implements DomainEntity {

    private Long id;
    private String fecha;
    private Integer carga;
    private long ejercicioId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Marca() {
    }

    public Marca(Long id) {
        this.id = id;
    }

    public Marca(Long id, String fecha, Integer carga, long ejercicioId) {
        this.id = id;
        this.fecha = fecha;
        this.carga = carga;
        this.ejercicioId = ejercicioId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFecha() {
        return fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    public Integer getCarga() {
        return carga;
    }

    public void setCarga(Integer carga) {
        this.carga = carga;
    }

    public long getEjercicioId() {
        return ejercicioId;
    }

    public void setEjercicioId(long ejercicioId) {
        this.ejercicioId = ejercicioId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
