package com.fitnesstime.fitnesstime.Dominio;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PASO".
 */
public class Paso implements DomainEntity {

    private Long id;
    /** Not-null value. */
    private String idUsuario;
    private Integer pasosDados;
    private String fecha;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Paso() {
    }

    public Paso(Long id) {
        this.id = id;
    }

    public Paso(Long id, String idUsuario, Integer pasosDados, String fecha) {
        this.id = id;
        this.idUsuario = idUsuario;
        this.pasosDados = pasosDados;
        this.fecha = fecha;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getIdUsuario() {
        return idUsuario;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }

    public Integer getPasosDados() {
        return pasosDados;
    }

    public void setPasosDados(Integer pasosDados) {
        this.pasosDados = pasosDados;
    }

    public String getFecha() {
        return fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
