package com.fitnesstime.fitnesstime.Dominio;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SECURITY_TOKEN".
 */
public class SecurityToken implements DomainEntity {

    private Long id;
    /** Not-null value. */
    private String nombreUsuario;
    /** Not-null value. */
    private String emailUsuario;
    private String imagenPerfil;
    /** Not-null value. */
    private String authToken;
    /** Not-null value. */
    private String fechaNacimientoUsuario;
    /** Not-null value. */
    private String pesoUsuario;
    /** Not-null value. */
    private String cantidadMinimaPasosUsuario;

    public SecurityToken() {
    }

    public SecurityToken(Long id) {
        this.id = id;
    }

    public SecurityToken(Long id, String nombreUsuario, String emailUsuario, String imagenPerfil, String authToken, String fechaNacimientoUsuario, String pesoUsuario, String cantidadMinimaPAsosUsuario) {
        this.id = id;
        this.nombreUsuario = nombreUsuario;
        this.emailUsuario = emailUsuario;
        this.imagenPerfil = imagenPerfil;
        this.authToken = authToken;
        this.fechaNacimientoUsuario = fechaNacimientoUsuario;
        this.pesoUsuario = pesoUsuario;
        this.cantidadMinimaPasosUsuario = cantidadMinimaPAsosUsuario;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getNombreUsuario() {
        return nombreUsuario;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }

    /** Not-null value. */
    public String getEmailUsuario() {
        return emailUsuario;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmailUsuario(String emailUsuario) {
        this.emailUsuario = emailUsuario;
    }

    public String getImagenPerfil() {
        return imagenPerfil;
    }

    public void setImagenPerfil(String imagenPerfil) {
        this.imagenPerfil = imagenPerfil;
    }

    /** Not-null value. */
    public String getAuthToken() {
        return authToken;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAuthToken(String authToken) {
        this.authToken = authToken;
    }

    /** Not-null value. */
    public String getFechaNacimientoUsuario() {
        return fechaNacimientoUsuario;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFechaNacimientoUsuario(String fechaNacimientoUsuario) {
        this.fechaNacimientoUsuario = fechaNacimientoUsuario;
    }

    /** Not-null value. */
    public String getPesoUsuario() {
        return pesoUsuario;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPesoUsuario(String pesoUsuario) {
        this.pesoUsuario = pesoUsuario;
    }

    /** Not-null value. */
    public String getCantidadMinimaPasosUsuario() {
        return cantidadMinimaPasosUsuario;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCantidadMinimaPasosUsuario(String cantidadMinimaPAsosUsuario) {
        this.cantidadMinimaPasosUsuario = cantidadMinimaPAsosUsuario;
    }

}
