package com.fitnesstime.fitnesstime.Dominio;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SECURITY_TOKEN".
 */
public class SecurityToken implements DomainEntity {

    private Long id;
    /** Not-null value. */
    private String nombreUsuario;
    /** Not-null value. */
    private String emailUsuario;
    /** Not-null value. */
    private String authToken;

    public SecurityToken() {
    }

    public SecurityToken(Long id) {
        this.id = id;
    }

    public SecurityToken(Long id, String nombreUsuario, String emailUsuario, String authToken) {
        this.id = id;
        this.nombreUsuario = nombreUsuario;
        this.emailUsuario = emailUsuario;
        this.authToken = authToken;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getNombreUsuario() {
        return nombreUsuario;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }

    /** Not-null value. */
    public String getEmailUsuario() {
        return emailUsuario;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmailUsuario(String emailUsuario) {
        this.emailUsuario = emailUsuario;
    }

    /** Not-null value. */
    public String getAuthToken() {
        return authToken;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAuthToken(String authToken) {
        this.authToken = authToken;
    }

}
